"""
Builds the model card accompanying a downloadable model, per SDD §17.
Deliberately derives input_schema from the saved Pipeline at request
time (via feature_names_in_) rather than storing it as a new DB column
-- avoids a schema migration for something fully recoverable from the
artifact that's already being loaded anyway.
"""

from datetime import datetime, timezone

from app.modules.storage import model_storage

MITIGATION_DESCRIPTIONS = {
    "Reweighing": (
        "Reweighing is a pre-processing bias mitigation technique that "
        "assigns higher training weight to underrepresented "
        "(group, outcome) combinations, so the model learns from a "
        "fairness-adjusted view of the training data without changing "
        "the raw records themselves."
    ),
}


def build_model_card(version, run) -> dict:
    input_schema = None
    try:
        pipeline = model_storage.load_model(version.artifact_path)
        feature_names = getattr(pipeline, "feature_names_in_", None)
        if feature_names is not None:
            input_schema = {"expected_features": list(feature_names)}
    except Exception:
        # Model card generation should never hard-fail just because the
        # schema couldn't be introspected -- the rest of the card is
        # still useful without it.
        input_schema = None

    return {
        "version_id": version.version_id,
        "parent_version_id": version.parent_version_id,
        "run_id": version.run_id,
        "version_number": version.version_number,
        "algorithm": version.algorithm_name,
        "source": version.source,
        "mitigation_method": version.mitigation_method,
        "mitigation_description": MITIGATION_DESCRIPTIONS.get(version.mitigation_method),
        "protected_attribute_configuration": {
            "protected_attribute": run.protected_attribute,
            "privileged_value": run.privileged_value,
            "unprivileged_value": run.unprivileged_value,
        },
        "library_versions": version.library_versions,
        "hyperparameters": version.hyperparameters,
        "performance_metrics": version.performance_metrics,
        "fairness_metrics": version.fairness_metrics,
        "input_schema": input_schema,
        "preprocessing_status": version.preprocessing_status,
        "preprocessing_disclosure": (
            "This model was uploaded as a bare estimator (not a Pipeline). "
            "Preprocessing of input data is assumed to match the original "
            "training process and could not be independently verified."
            if version.preprocessing_status == "user_responsibility"
            else "Preprocessing is fully managed by this model's own Pipeline; "
            "raw feature values matching input_schema can be passed directly."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": (
            "This model card was generated by an internal Responsible AI "
            "platform. It is intended to support, not replace, human "
            "review, and is not a certified fairness or compliance audit."
        ),
    }
